### ISSUE TITLE
Better support for conditional classes?

### ISSUE THREAD

**Issue by jakelowen** [FullHuman/purgecss#136]
**Is your feature request related to a problem? Please describe.**
Purgecss is awesome. I do have one frustrating situation that I often encounter when I conditionally apply classes in my react app based on props/state. Because those classes are not present on the first render and only conditionally applied after the fact, I find that I must manually add any conditional class to the purgecss whitelist so that it is present when it needs to be. 

Example:
```
 <header
        style={{
          top: scrolled && typeof position === "number" ? position : "auto"
        }}
        className={cx(
          {
            fixed: scrolled,
            relative: !scrolled
          },
          "w-100"
        )}
      >
        {children}
      </header>
```

in this example the "w-100" class is included, but the "fixed" and "relative" classes are not. It would be very nice if there was some way to avoid manually white listing all the conditional classes. That seems fragile over the long term. Am I missing some way to automate this with postcss / webpack?

**Comment by jsnanigans** [comment]
This should be done by the extractor if you are using the default extractor `[A-Za-z0-9_-]+` then it should be fine but i'm not sure if its different in jsx/react, could you share how you are implementing purgecss?

**Comment by jakelowen** [comment]
Purge Implementation here:
https://github.com/jakelowen/nextjs-tailwind-purgecss-flow/blob/master/next.config.js

Most of the configuration is done using the "next-purgecss" module.

**Comment by jsnanigans** [comment]
your issue is with the tailwind extractor.. because tailwind uses `:` inside the classes the extractor sees it as part of the selector so when it sees `fixed:` it will think that the `:` belongs to the class, there are two easy ways you could avoid this: 

1. Add a space between the object key and the `:`. your linter might complain about this though
2. put the key into some apostrophes

you can test this all by going to regexpal and pasting in the extractor and the jsx, then you'll see something like this (I added the artful lines to indicate which one will work):
![selection_068](https://user-images.githubusercontent.com/4624141/45156600-ff5de600-b1de-11e8-8097-08255b305762.png)

The best solution would probably be to modify the extractor to not include the `:` if its the last symbol but I'm not sure how to do that with regex

**Comment by jakelowen** [comment]
Very helpful tip. Thank you!  I'll wrestle a bit with modifying the extractor regex otherwise I'll end up fighting a battle with linter + prettier. If I work it out I will post it here for anyone else who may stumble upon it.

**Comment by masone** [comment]
Here's the regex that worked for me (making sure there is no colon at the end):
```
/[A-Za-z0-9-_:\/]+(?<!:)/g
```

**Comment by cliffordp** [comment]
For anyone else who later finds this issue and is using PurgeCSS **v2+**, Tailwind provides the regex and setup for us here: https://tailwindcss.com/docs/controlling-file-size/#setting-up-purgecss

**Comment by vpattar** [comment]
I am using the [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin) which is extracting the styles properly in to css file, but when I configure purgecss webpack plugin they are deleted. Am I doing anything wrong or can I override this (there are lot of instances where cx is used for me to whitelist all of them.
