### ISSUE TITLE
Classes that start with `:` are incorrectly kept

### ISSUE THREAD

**Issue by stowball** [FullHuman/purgecss#194]
**Describe the bug**

Any classes that start with `:` (such as `:hocus-color-red`) are always kept, regardless of whether they're used or not due to this line: https://github.com/FullHuman/purgecss/blob/master/src/index.js#L438

```
if (unescapedSelector.startsWith(':')) {
    continue
}
```

**To Reproduce**

Create the following:

##### CSS

```css
.\:colon-prefix-to-stay { color: green; }
.\:colon-prefix-to-remove { color: red; }
```

##### HTML

```html
<div class=":colon-prefix-to-stay"></div>
```

##### Extractor

```js
extractor: class {
  static extract(content) {
    return content.match(/[A-Za-z0-9-:]+/g) || [];
  }
}
```

**Expected behavior**

Only 1 class should remain after purging: `.:colon-prefix-to-stay`

**Desktop**
 - OS: macOS
 - Purgecss v1.2.0

**Additional context**

This "bug" basically ruins my CSS library 😬

**Comment by leeoniya** [comment]
you might consider using a workaround like this:

https://github.com/leeoniya/dropcss#special--escaped-sequences

**Comment by stowball** [comment]
Hmmm I can't really ask all my potential users to set up a system to rewrite their entire HTML and back again to workaround this. It would basically kill its adoption

**Comment by leeoniya** [comment]
i don't quite follow. you already advise users to use a purge step with a custom extractor [1]. the small difference would be that they simply run their html and css through an escaping function before the purge and unescaping function after. which adds like 3 lines to the code (assuming you provide them the util functions). anyways, ideally it can be fixed in PurgeCSS.

by the looks of it, the un-escaping seems premature:

https://github.com/FullHuman/purgecss/blob/master/src/index.js#L435-L440

```js
// pseudo class
const unescapedSelector = selector.replace(/\\/g, '')

if (unescapedSelector.startsWith(':')) {
  continue
}
```

pseudo-classes would begin with `:` in the original escaped form, so this would probably fix it:


```js
// pseudo class
if (selector.startsWith(':')) {
  continue
}

const unescapedSelector = selector.replace(/\\/g, '')
```



[1] https://github.com/stowball/hucssley#controlling-file-size
