### ISSUE TITLE
Allow whitelist feature work with double slash comments

### ISSUE THREAD

**Issue by xavierfoucrier** [FullHuman/purgecss#224]
Hi,

I am using `PurgeCSS` through the `purgecss-webpack-plugin`. As my source contains a mix of `less` and `sass` files, I would like to be able to **use double slash quotes** to ignore a range of rules.

Current working example:
```less
/* purgecss start ignore */
.whitelisted { ... }
/* purgecss end ignore */
```

Using a double slash comment, PurgeCSS will **ignore the comment**:
```less
// purgecss start ignore
.should-be-whitelisted { ... }
// purgecss end ignore
```

This is the same for single rule whitelisting...

> purgecss-webpack-plugin@1.6.0 + webpack@4.40.2

**Comment by n1kk** [comment]
I don't think this is relevant to PostCSS per se. Your LESS/SASS styles are probably being processed before PostCSS and since double slash comments are not a valid CSS syntax they most likely are removed before code gets passed down to PostCSS. 

You can try enabling some settings to preserve comments in LESS/SASS, maybe that way they will be converted from `//` to a valid css format so they would work in PostCSS.

**Comment by xavierfoucrier** [comment]
Hi @n1kk,

Sorry for the late reply!

Thanks for the explanation, in fact, I have found that double slash comments in `LESS` are **silent comments**, which mean that they won't appear in the CSS output as per documentation states:

> Single-line comments are also valid in LESS, but they are ‘silent’, they don’t show up in the compiled CSS output:

Anyway, this allow me to understand that it's not PurgeCSS related :wink: 
Closing the issue.
