### ISSUE TITLE
Option to not include class names in source markup comments

### ISSUE THREAD

**Issue by YoungElPaso** [FullHuman/purgecss#297]
Problem:
I don't know if this is intentional or not (I could see a case being made either way) but by default if I have a class name in a comment in my source file (e.g. index.js) that class is considered 'used' and so bundled in the final CSS output. 

E.g.
```
import './styles.css';

// .bar indicates something special. 
let foo = `<span class="bar">Foobar</span>`; // Good, .bar should be output.

// .regular indicates regular styles.
// let reg = `<span class="regular">Normal. </span>`; 
// Dunno if all these commented out matches on 'regular' should result in output.
```

I can appreciate that some might say: "well its in the code, so it's in use" and I agree that this should be an option (you might be illustrating that some class *might* exist asynchronously or something), but I'm not sure it should be the default behaviour.

At the moment this results in a lot of what I consider false-positives and outside of using a different extractor I don't see much of a solution.

Potential Solution:
Ideally, a configuration option to ignore source comments could be added and set to true and used in the default extractor.

**Comment by Ffloriel** [comment]
It is by design. The problem is that you have different types of files as inputs. Javascript, Html, Blade, Pug, Twig, Yaml eventually,... all have different ways of expressing comments.
PurgeCSS is by design generic but this behavior can be changed. You can use a different extractor that will include selectors based on the type of file.
