### ISSUE TITLE
Use PurgeCSS only for a package coming from node_modules?

### ISSUE THREAD

**Issue by Alex-Ferreli** [FullHuman/purgecss#310]
Hi, i'm trying to use PurgeCSS only for a specified package installed via NPM (Tailwindcss).

The problem is that when i use Tailwindcss with other package, antd for example, PurgeCSS remove all unused CSS classes generated from Tailwindcss, but also remove some used classes added from antd.

This is caused because antd concat classes, and PurgeCSS can't find that concatenated classes with his regex.

So if a project is using at least 1 dependencies that concat classes PurgeCSS remove usefull classes used at runtime, not recognized during build step.

It's possible to apply PurgeCSS only on specific package? I would apply PurgeCSS only to Tailwindcss, without touch other packages.

There is the issue that i posted to antd repo, asking to not concat classes to make antd purgable, without success: https://github.com/ant-design/ant-design/issues/20823

In the same issue there is my test repo explaning the issue: https://github.com/Alex-Ferreli/antd-purgecss-issue

The repo isn't updated with the latest version of PurgeCSS but this is not a feature/bug fixed in 2.0 (or at least, the fix isn't documented yet maybe), do you want an updated version of the same repo?

Thanks for the awesome work, the possibility to eliminate all unused classes is awesome!

**Comment by janko** [comment]
I'm looking to do the same thing. I also use TailwindCSS and want to scope PurgeCSS only to these styles.

What could solve my problem is to be able to configure PurgeCSS to be opt-in rather than opt-out. For example, rather than having to `/* purgecss ignore */` around what I need skipped, I would like to instead e.g. `/* purgecss enable */` around the CSS I want to purge, and have everything else skipped by default.

Alternatively, we could have the ability to specify CSS files that we want purged (and everything else is skipped by default). I thought the `css` option was already doing that, but for me it didn't have any effect.

I think this feature would make PurgeCSS much more useful, as it would allow minimizing the risk of removing styles we actually need, by minimizing its scope.

**Comment by Alex-Ferreli** [comment]
@janko i have found a solution.

This is the repo: https://github.com/Alex-Ferreli/tailwindcss-purgecss-example

The second commit is the key commit, the entire setup to make the project work.

I have created a different css file with only tailwind css.

In pre-start command tailwind css is generated, based on the configuration (in the repo i activate all possibly variants, to have the full list of classes avaiable in DEV).

In the pre-build command, tailwind css is generated and PurgeCSS is called only on this file, to remove all unused tailwind classes.

The css generated by tailwind must be imported in index.tsx file (the entrypoint on react projects).

If something is not clear just ask to me, i will explain all doubt about the repo.

**Comment by dhazeley** [comment]
@Alex-Ferreli

This is the best solution I've found from hours of searching online so far and it's not a complicated at all. Thanks for sharing

**Comment by Alex-Ferreli** [comment]
@dhazeley i'm glad that my solution helped you! I'm using it in a personal project and it's perfect. I have found only a bug, i have fixed it in the latest commit, go check it out.

For some reason the responsive classes (or classes with ":") were removed from the final bundle. Latest commit fixed it.
