### ISSUE TITLE
Purge not accurate

### ISSUE THREAD

**Issue by MartinHotmann** [FullHuman/purgecss#657]
**Describe the bug**

**To Reproduce**
1. Optimize Bootstrap against a HTML which contains one normal `<small>testText</small>`
2. see in the bootstrap this CSS:
```
.small,small{
    font-size:.875em
}
```
3. make sure you never used the class "small" (`.small`) but the element instead (`<small>`)
4. expected result is this output (unused Class removed):
```
small{
    font-size:.875em
}
```
but instead this particular CSS block is not altered at all and stays like this:
```
.small,small{
    font-size:.875em
}
```

Same happens for the Bootstrap ul CSS code:

```
ul ul {
  margin-bottom: 0; 
}
```
This CSS 100% never applies on any of my HTML files but still it is not getting purged.
Here the expected result would be that the unused CSS would be removed completely.

**Environment (please complete the following information):**
 - Package: grunt-purgecss
 - Version: 4.0.3

**Comment by sselvaggi** [comment]
Hi @MartinHotmann  
If the rule is stil relevant. Why do you wish to remove the 2nd selector?

**Comment by Ffloriel** [comment]
This lack of accuracy is expected.
For the distinction between `small` and `.small`, you will need to use an extractor like `purgecss-from-html` that will be able to distinguish between classes, ids, attributes. By default, there's no distinction made between the two. And since we don't know if `small` found in the content is an id, class, element, attributes, every variation will be kept in the CSS (id, classes, attributes, ...).
