### ISSUE TITLE
CSS_SAFELIST: add <body> and <html> tag

### ISSUE THREAD

**Issue by zh-lx** [FullHuman/purgecss#843]
**Is your feature request related to a problem? Please describe.**
When I pack with webpack, my `body` and `html` styles are always removed and I need to manually add them to CSS_SAFELIST.

**Describe the solution you'd like**
The `body` and `html` tags are a must on every page, I think they should be added to the CSS_SAFELIST.

**Comment by Ffloriel** [comment]
PurgeCSS will not remove the body and html styles if they are present in the content.
If your `body` and `html` styles are removed all the times, it's because it is not included in your content.

With something like create-react-app, there is a public.html file with `html` and `body` that should also be included.
From my perspective, PurgeCSS is acting properly here: not in the content -> remove the styles. The fact that some frameworks like Next.js have the outer document (with the `html` and `body` tags) hidden is not a PurgeCSS issue.
